apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: todo-items.matiasmartin00.com
spec:
  group: matiasmartin00.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                completed:
                  type: boolean
              required:
                - title
                - completed
  scope: Namespaced
  names:
    plural: todo-items
    singular: todo-item
    kind: TodoItem
    shortNames:
      - ti