---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - matiasmartin00.matiasmartin00.com
  resources:
  - todoitems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matiasmartin00.matiasmartin00.com
  resources:
  - todoitems/finalizers
  verbs:
  - update
- apiGroups:
  - matiasmartin00.matiasmartin00.com
  resources:
  - todoitems/status
  verbs:
  - get
  - patch
  - update
